// <auto-generated />
using System;
using Customer.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Customer.Infrastructure.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Customer.Infrastructure.Database.Tables.CustomerDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalMonthsOfMembership")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Customer.Infrastructure.Database.Tables.CustomerDB", b =>
                {
                    b.OwnsOne("Customer.Infrastructure.Database.Tables.EmailDb", "EmailDb", b1 =>
                        {
                            b1.Property<Guid>("CustomerDBId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CustomerDBId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerDBId");
                        });

                    b.OwnsOne("Customer.Infrastructure.Database.Tables.MembershipDb", "MembershipDb", b1 =>
                        {
                            b1.Property<Guid>("CustomerDBId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("SubscriptionType")
                                .HasColumnType("int");

                            b1.HasKey("CustomerDBId");

                            b1.ToTable("Customers");

                            b1.HasAnnotation("ColumnName", "Membership");

                            b1.WithOwner()
                                .HasForeignKey("CustomerDBId");
                        });

                    b.OwnsOne("Customer.Infrastructure.Database.Tables.NameDb", "NameDb", b1 =>
                        {
                            b1.Property<Guid>("CustomerDBId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CustomerDBId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerDBId");
                        });

                    b.OwnsOne("Customer.Infrastructure.Database.Tables.PhoneNumberDb", "NumberDb", b1 =>
                        {
                            b1.Property<Guid>("CustomerDBId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CustomerDBId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerDBId");
                        });

                    b.Navigation("EmailDb")
                        .IsRequired();

                    b.Navigation("MembershipDb")
                        .IsRequired();

                    b.Navigation("NameDb")
                        .IsRequired();

                    b.Navigation("NumberDb")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
